---
title: 'Case Study : ODI'
author: "Barun Kumar"
output: html_document
---

```{r}

source("D:/DSML-M/SEM1/R Language/utils.R") #Fetch user defined function from directory
odi = read.csv("D:/DSML-M/SEM1/R Language/CSV files/odi-batting.csv")
head(odi)
```

List count of values which are not NA in all colummns

```{r}

na_sum <- sapply(odi, function(x) sum(is.na(x)))
na_sum

```

List all column names

```{r}

for (col in colnames(odi)){
  print(col)
}

```

List count of Na's in each column

```{r}

for (col in colnames(odi)){
  print(c(col,sum(is.na(odi[,col]))))
}

```


List % of Na's in each column

```{r}

calc_perc_na <- function(df){
  return(colSums(is.na(df))/nrow(df) * 100)
}

calc_perc_na(odi)

```

List levels in given columns of dataset

```{r}

calc_nlevels <- function(df){
  abc = list()
  for(col in colnames(df)){
    abc[col] <- length(unique(df[,col]))
  }
  return(abc)
}

calc_nlevels(odi[,c('Country','Player')])

```

List most repeated item in each column


```{r}

calc_most_freq <- function(df){
  qr = list()
  for(col in colnames(df)){
   qr[col] <- labels(sort(table(df[,col]),decreasing = TRUE)[1])
  }
  return(qr)
}


calc_most_freq(odi)

```

summary for categorical columns of odi dataset

```{r}

summary_df <- function(df){
  row_3 = calc_perc_na(df)
  row_2 <- calc_nlevels(df)
  row_1 <- calc_most_freq(df)
  result <- rbind(most_freq = row_1,
                  unique_levels = row_2,
                  perc_na = row_3)
  return(data.frame(result))
}

View(summary_df(odi[,c('Country','Player')]))

```
